#!/usr/bin/env bash

export SERVER_PORT=9083
export LOGGING_LEVEL_ROOT=INFO
export LOGGING_LEVEL_COM_GIRAONE=INFO
export SPRING_APPLICATION_NAME=consume
export SPRING_KAFKA_CLIENT_ID=${SPRING_APPLICATION_NAME}
export SPRING_KAFKA_CONSUMER_GROUP_ID=${SPRING_APPLICATION_NAME}
export APPLICATION_MODE=${1:-Consume}
export APPLICATION_TOPIC_B=${3:-b1}

java -jar target/atleon-kafka.jar
