#!/usr/bin/env bash

export SERVER_PORT=9082
export LOGGING_LEVEL_COM_GIRAONE=INFO
export SPRING_APPLICATION_NAME=pipe
export SPRING_KAFKA_CLIENT_ID=${SPRING_APPLICATION_NAME}
export SPRING_KAFKA_CONSUMER_GROUP_ID=${SPRING_APPLICATION_NAME}
export APPLICATION_MODE=${1:-PipeReceiveSend}
export APPLICATION_TOPIC_A=${2:-a1}
export APPLICATION_TOPIC_B=${3:-b1}
export APPLICATION_PROCESSING_TIME=${5:-50ms}
export APPLICATION_CONSUMER_SCHEDULER_TYPE=${6:-newParallel}

java -jar target/atleon-kafka.jar
